version: '3.4'
services:
  netbox:
    ports:
    - 8080:8080
    volumes:
    - /mnt/docker/netbox/config:/etc/netbox/config:z,ro
    - /mnt/docker/netbox/netbox-media-files:/opt/netbox/netbox/media:z,rw
    - /mnt/docker/netbox/netbox-reports-files:/opt/netbox/netbox/reports:z,rw
    - /mnt/docker/netbox/netbox-scripts-files:/opt/netbox/netbox/scripts:z,rw
    healthcheck:
      retries: 15
  netbox-worker:
    volumes:
    - /mnt/docker/netbox/config:/etc/netbox/config:z,ro
    - /mnt/docker/netbox/netbox-media-files:/opt/netbox/netbox/media:z,rw
    - /mnt/docker/netbox/netbox-reports-files:/opt/netbox/netbox/reports:z,rw
    - /mnt/docker/netbox/netbox-scripts-files:/opt/netbox/netbox/scripts:z,rw
  netbox-housekeeping:
    volumes:
    - /volume1/docker/netbox:/etc/netbox/config:z,ro
    - /mnt/docker/netbox/netbox-media-files:/opt/netbox/netbox/media:z,rw
    - /mnt/docker/netbox/netbox-reports-files:/opt/netbox/netbox/reports:z,rw
    - /mnt/docker/netbox/netbox-scripts-files:/opt/netbox/netbox/scripts:z,rw
  postgres:
    volumes:
      - /mnt/docker/netbox/netbox-postgres-data:/var/lib/postgresql/data
